# Generated by Django 2.2.6 on 2021-08-18 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='MyImage')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
